env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1
  quotes:
    - error
    - single
  semi:
    - error
    - always
  object-curly-spacing:
    - error
    - always
  eol-last:
    - error
    - always
  no-multiple-empty-lines:
    - 2
  space-before-function-paren:
    - error
    - never
